### ISSUE TITLE
Link to Child Registration Form

### ISSUE THREAD

**Issue by communicationsmare** [autoboxer/MARE#132]
If possible, child registration form should link to "Register a child" heading on Register a Child tab.  It is also linked in text but ideally would be both.  There should also be a prompt that worker has to log-in before proceeding if they aren't already.

**Comment by autoboxer** [comment]
The page at `/page/register-a-child` needs to link to the register a child form.  If the user isn't a logged in social worker, they shouldn't see the link (we'll need to determine the change in text), and if they are logged in, they will see it.  Social Workers may see slightly different text than other users.

**Comment by autoboxer** [comment]
We need to make it easier to find the register a child form.
