### ISSUE TITLE
Social media links

### ISSUE THREAD

**Issue by communicationsmare** [autoboxer/MARE#135]
Assign to Anna

Program links to our FB, Twitter and Instagram accounts, and maybe a blog placeholder?    No pintrest or You Tube icons.

blog: https://wordpress.com/design/adoptionfromfostercare.wordpress.com
facebook: Massachusetts Adoption Resource Exchange
twitter: mass_adopt
instagram: mass_adopt

**Comment by autoboxer** [comment]
Lisa is sending over the links, bother her about them if she doesn't. [ 1-3-2017 ]

**Comment by communicationsmare** [comment]
Jared should have links.
