### ISSUE TITLE
MARE in the news

### ISSUE THREAD

**Issue by communicationsmare** [autoboxer/MARE#139]
Where is MARE in the News tab pulling from?  I don't see any content pages associated with this tab.

**Comment by autoboxer** [comment]
This page was never created, and can be made in the admin ui at `development.adoptions.io/keystone` after logging in as an admin user.  The only requirement for it to link correctly is the name be `'MARE in the News'` ( this is case insensitive, so capitalize as you see fit ).

**Comment by communicationsmare** [comment]
Is it possible to change this to capital MARE for Mare in the news page for consistency.

**Comment by autoboxer** [comment]
@communicationsmare, I Updated the page header to capitalize MARE.
