### ISSUE TITLE
wire up have a question form

### ISSUE THREAD

**Issue by communicationsmare** [autoboxer/MARE#146]
The Have a Question Form should have the heading "Event Details" Removed.  And the link to "Considering Adoption" does not work.  Should either read our Considering Adoption Pages, or link to "Can I adopt a child from Foster care" page.  Thoughts welcome!?

Make sure Bridget and Lisa send you the list of email opt-outs to add at the bottom of the form.

**Note:** The have a question form is a physical printout someone in the pile of documents you've collected over the years.  Good luck!

**Comment by autoboxer** [comment]
the link should go to the `can I adopt a child from foster care` page.
