### ISSUE TITLE
data migration - create scripts to save data into the new system

### ISSUE THREAD

**Issue by autoboxer** [autoboxer/MARE#23]
Below are candidates for migration from the old system to the new one.  @lisa will be able to give a better idea of what should be migrated.  It should be noted that several tables listed below can be combined in the creation of a single object in the new system.

[full database export](https://github.com/autoboxer/MARE/files/252196/database_schema.txt)

Database export - individual table creation scripts:

[agency_contact.txt](https://github.com/autoboxer/MARE/files/252168/agency_contact.txt)
[agency.txt](https://github.com/autoboxer/MARE/files/252169/agency.txt)
[app_user.txt](https://github.com/autoboxer/MARE/files/252170/app_user.txt)
[call.txt](https://github.com/autoboxer/MARE/files/252171/call.txt)
[child_history.txt](https://github.com/autoboxer/MARE/files/252172/child_history.txt)
[child.txt](https://github.com/autoboxer/MARE/files/252173/child.txt)
[event_attendee.txt](https://github.com/autoboxer/MARE/files/252174/event_attendee.txt)
[event.txt](https://github.com/autoboxer/MARE/files/252175/event.txt)
[extranet_automatic_inquiry_history.txt](https://github.com/autoboxer/MARE/files/252176/extranet_automatic_inquiry_history.txt)
[extranet_family.txt](https://github.com/autoboxer/MARE/files/252177/extranet_family.txt)
[extranet_inquiry.txt](https://github.com/autoboxer/MARE/files/252178/extranet_inquiry.txt)
[extranet_notification_queue.txt](https://github.com/autoboxer/MARE/files/252179/extranet_notification_queue.txt)
[family_child.txt](https://github.com/autoboxer/MARE/files/252180/family_child.txt)
[family_contact.txt](https://github.com/autoboxer/MARE/files/252181/family_contact.txt)
[family_history.txt](https://github.com/autoboxer/MARE/files/252182/family_history.txt)
[family_placement.txt](https://github.com/autoboxer/MARE/files/252183/family_placement.txt)
[family.txt](https://github.com/autoboxer/MARE/files/252184/family.txt)
[file_attachment.txt](https://github.com/autoboxer/MARE/files/252185/file_attachment.txt)
[mailing_list_subscription.txt](https://github.com/autoboxer/MARE/files/252188/mailing_list_subscription.txt)
[mailing_list.txt](https://github.com/autoboxer/MARE/files/252186/mailing_list.txt)
[outside_contact.txt](https://github.com/autoboxer/MARE/files/252187/outside_contact.txt)
[pending_termination_item.txt](https://github.com/autoboxer/MARE/files/252189/pending_termination_item.txt)
[pending_termination.txt](https://github.com/autoboxer/MARE/files/252190/pending_termination.txt)
[recruitment_action.txt](https://github.com/autoboxer/MARE/files/252191/recruitment_action.txt)
[recruitment_checklist.txt](https://github.com/autoboxer/MARE/files/252192/recruitment_checklist.txt)

**Comment by lisa** [comment]
@autoboxer I think you mean a different Lisa?

**Comment by autoboxer** [comment]
Why yes I did, I wasn't aware I could tag people from outside my collaborators list.  Sorry about that!
